spring:
  application:
    name: auth-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  security:
    user:
      name: none
      password: none

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/auth_service_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: ${PORT:8081}

app:
  jwt:
    secret: ${JWT_SECRET:UneCleSecreteTresLonguePourSignerLeJwtEtLaValiderAuthService2026}
    expiration: ${JWT_EXPIRATION:86400000}