spring:
  application:
    name: auth-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  security:
    user:
      name: none
      password: none

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081

app:
  jwt:
    secret: "UneCleSecreteTresLonguePourSignerLeJwtEtLaValiderAuthService2026"
    expiration: 86400000